### ISSUE TITLE
Design, Code, & Launch Landing Page

### ISSUE THREAD

**Issue by TravisWyche** [yeet-haus/site#6]
Need to make a landing page for Yeeter v2.
Should provide the quick high level pitch for the product and a link to the app.
Need to align on what content needs to be here: copy text, visual, diagrams, links, etc.
Setup `yeet.haus` to direct to this site when it's ready.
Needs to be responsive for all screens and look especially sexy on mobile.

**Comment by earth2travis** [comment]
Digging the square in the background
